
package Gui;

import gamecenter.Games;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JEditorPane;

/**
 *
 * @author u20o90
 */
public class GameNameSetting extends javax.swing.JDialog
{

    
    public ArrayList<String> gamelist;
    public GameNameSetting(java.awt.Frame parent, boolean modal) 
    {
    super(parent, modal);
    initComponents();
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (int) ((dimension.getWidth() - getWidth()) / 2);
    int y = (int) ((dimension.getHeight() - getHeight()) / 2);
    setLocation(x, y);
    gamelist = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AirHockey1 = new javax.swing.JCheckBox();
        AirHockey2 = new javax.swing.JCheckBox();
        Carracing1 = new javax.swing.JCheckBox();
        Carracing2 = new javax.swing.JCheckBox();
        DanceDance1 = new javax.swing.JCheckBox();
        Enginetrain2 = new javax.swing.JCheckBox();
        DanceDance2 = new javax.swing.JCheckBox();
        Helicopter = new javax.swing.JCheckBox();
        Spiderstorm = new javax.swing.JCheckBox();
        Basketball1 = new javax.swing.JCheckBox();
        TrackTrain2 = new javax.swing.JCheckBox();
        TrackTrain1 = new javax.swing.JCheckBox();
        Enginetrain1 = new javax.swing.JCheckBox();
        AddGameButton = new javax.swing.JButton();
        Basketball2 = new javax.swing.JCheckBox();
        Hammer = new javax.swing.JCheckBox();
        Speedball2 = new javax.swing.JCheckBox();
        Horse = new javax.swing.JCheckBox();
        Toycatcher = new javax.swing.JCheckBox();
        Rainbow = new javax.swing.JCheckBox();
        Speedball1 = new javax.swing.JCheckBox();
        Horse2 = new javax.swing.JCheckBox();
        toytrain1 = new javax.swing.JCheckBox();
        Paystation1 = new javax.swing.JCheckBox();
        catchlight1 = new javax.swing.JCheckBox();
        bikerace1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 529));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Check Game Names For Your Gamezone");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 360, 70);

        AirHockey1.setText("Air hockey-1");
        getContentPane().add(AirHockey1);
        AirHockey1.setBounds(110, 100, 140, 30);

        AirHockey2.setText("Air hockey-2");
        getContentPane().add(AirHockey2);
        AirHockey2.setBounds(110, 140, 120, 30);

        Carracing1.setText("Car racing-1");
        getContentPane().add(Carracing1);
        Carracing1.setBounds(110, 180, 110, 23);

        Carracing2.setText("Car racing-2 ");
        getContentPane().add(Carracing2);
        Carracing2.setBounds(110, 220, 120, 23);

        DanceDance1.setText("Dance Dance-1");
        getContentPane().add(DanceDance1);
        DanceDance1.setBounds(110, 260, 160, 23);

        Enginetrain2.setText("Engine train-2");
        getContentPane().add(Enginetrain2);
        Enginetrain2.setBounds(360, 210, 120, 23);

        DanceDance2.setText("Dance Dance-2");
        getContentPane().add(DanceDance2);
        DanceDance2.setBounds(110, 300, 130, 23);

        Helicopter.setText("Helicopter");
        getContentPane().add(Helicopter);
        Helicopter.setBounds(110, 340, 150, 23);

        Spiderstorm.setText("Spider storm");
        getContentPane().add(Spiderstorm);
        Spiderstorm.setBounds(530, 300, 150, 23);

        Basketball1.setText("Basketball-1");
        getContentPane().add(Basketball1);
        Basketball1.setBounds(360, 250, 120, 23);

        TrackTrain2.setText("Track Train-2");
        getContentPane().add(TrackTrain2);
        TrackTrain2.setBounds(360, 130, 160, 30);

        TrackTrain1.setText("Track Train-1");
        getContentPane().add(TrackTrain1);
        TrackTrain1.setBounds(360, 100, 150, 23);

        Enginetrain1.setText("Engine train-1");
        getContentPane().add(Enginetrain1);
        Enginetrain1.setBounds(360, 170, 130, 23);

        AddGameButton.setText("Submit");
        AddGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddGameButton);
        AddGameButton.setBounds(320, 460, 140, 40);

        Basketball2.setText("Basketball-2");
        getContentPane().add(Basketball2);
        Basketball2.setBounds(360, 290, 150, 23);

        Hammer.setText("Hammer - 1");
        getContentPane().add(Hammer);
        Hammer.setBounds(360, 340, 150, 23);

        Speedball2.setText("Speedball-2");
        getContentPane().add(Speedball2);
        Speedball2.setBounds(530, 260, 150, 23);

        Horse.setText("Horse -1");
        getContentPane().add(Horse);
        Horse.setBounds(530, 100, 150, 23);

        Toycatcher.setText("Toy catcher -1");
        getContentPane().add(Toycatcher);
        Toycatcher.setBounds(530, 140, 150, 23);

        Rainbow.setText("Rainbow");
        getContentPane().add(Rainbow);
        Rainbow.setBounds(530, 180, 150, 23);

        Speedball1.setText("Speedball-1");
        getContentPane().add(Speedball1);
        Speedball1.setBounds(530, 220, 150, 23);

        Horse2.setText("Horse -2");
        getContentPane().add(Horse2);
        Horse2.setBounds(530, 340, 130, 23);

        toytrain1.setText("Toy Train - 1");
        getContentPane().add(toytrain1);
        toytrain1.setBounds(110, 380, 120, 23);

        Paystation1.setText("Play Station - 1");
        getContentPane().add(Paystation1);
        Paystation1.setBounds(360, 380, 140, 23);

        catchlight1.setText("Catch Light -1 ");
        getContentPane().add(catchlight1);
        catchlight1.setBounds(530, 370, 120, 23);

        bikerace1.setText("Bike race -1");
        getContentPane().add(bikerace1);
        bikerace1.setBounds(110, 420, 160, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameButtonActionPerformed

        // TODO add your handling code here:Submit button add games
    if(AirHockey1.isSelected())
    {
      gamelist.add("Airhockey-1");
    }
    if(AirHockey2.isSelected())
    {
      gamelist.add("Airhockey-2");
    }
    
    
      if(DanceDance1.isSelected())
    {
      gamelist.add("Dance-1");
    }
    if(DanceDance2.isSelected())
    {
      gamelist.add("Dance-2");
    }
    
    
    
        
      if(Carracing1.isSelected())
    {
      gamelist.add("Carrace-1");
    }
    if(Carracing2.isSelected())
    {
      gamelist.add("Carrace-2");
    }
    
    
    
    if(Helicopter.isSelected())
    {
      gamelist.add("Helicopter");
    }
         
         
    if(TrackTrain1.isSelected())
    {
      gamelist.add("Trktrain-1");
    }
           
    if(TrackTrain2.isSelected())
    {
      gamelist.add("Trktrain-2");
    }
   
    
             
    if(Enginetrain1.isSelected())
    {
      gamelist.add("Engine train-1");
    }
           
    if(Enginetrain1.isSelected())
    {
      gamelist.add("Engine train-2");
    }
   
      if(Basketball1.isSelected())
    {
      gamelist.add("Basketball-1");
    }
           
    if(Basketball2.isSelected())
    {
      gamelist.add("Basketball-2");
    }
   
    
 
     if(Hammer.isSelected())
    {
      gamelist.add("Hammer-1");
    }
           
    if(Horse.isSelected())
    {
      gamelist.add("Horse-1");
    }
    
    if(Horse2.isSelected())
    {
      gamelist.add("Horse-2");
    }
     
     if(Toycatcher.isSelected())
    {
      gamelist.add("Toycatcher-1");
    }
           
    if(Rainbow.isSelected())
    {
      gamelist.add("Rainbow");
    }
    
    
         
     if(Speedball1.isSelected())
    {
      gamelist.add("Speedball-1");
    }
           
    if(Speedball2.isSelected())
    {
      gamelist.add("Speedball-2");
    }
    
    
               
    if(Spiderstorm.isSelected())
    {
      gamelist.add("Spiderstorm");
    }
    
    if(toytrain1.isSelected())
    {
        gamelist.add("Toytrain-1");
    }
    
    
     if(Paystation1.isSelected())
    {
        gamelist.add("Playstn-1");
    }
     
    if(catchlight1.isSelected())
    {
      gamelist.add("Catchlight-1");
    }
    
    if(bikerace1.isSelected())
    {
      gamelist.add("Bikerace-1");
    }
        setVisible(false);
    
    }//GEN-LAST:event_AddGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameNameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameNameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameNameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameNameSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddGameButton;
    private javax.swing.JCheckBox AirHockey1;
    private javax.swing.JCheckBox AirHockey2;
    private javax.swing.JCheckBox Basketball1;
    private javax.swing.JCheckBox Basketball2;
    private javax.swing.JCheckBox Carracing1;
    private javax.swing.JCheckBox Carracing2;
    private javax.swing.JCheckBox DanceDance1;
    private javax.swing.JCheckBox DanceDance2;
    private javax.swing.JCheckBox Enginetrain1;
    private javax.swing.JCheckBox Enginetrain2;
    private javax.swing.JCheckBox Hammer;
    private javax.swing.JCheckBox Helicopter;
    private javax.swing.JCheckBox Horse;
    private javax.swing.JCheckBox Horse2;
    private javax.swing.JCheckBox Paystation1;
    private javax.swing.JCheckBox Rainbow;
    private javax.swing.JCheckBox Speedball1;
    private javax.swing.JCheckBox Speedball2;
    private javax.swing.JCheckBox Spiderstorm;
    private javax.swing.JCheckBox Toycatcher;
    private javax.swing.JCheckBox TrackTrain1;
    private javax.swing.JCheckBox TrackTrain2;
    private javax.swing.JCheckBox bikerace1;
    private javax.swing.JCheckBox catchlight1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox toytrain1;
    // End of variables declaration//GEN-END:variables
}
